// Illustrator engine adapter — drives the desktop app via ExtendScript.
//
// Strategy:
//   1. Resolve the template's source .ai file from job.template.source_ref
//      (bridge://templates/<filename> → ./templates/<filename> relative to
//      LOVABLE_AGENT_TEMPLATES, default ./templates).
//   2. Render a .jsx script that opens the doc, substitutes text/colour layers
//      from job.variables, exports a PNG + PDF to a temp folder, then closes.
//   3. Invoke Illustrator with the script (macOS: osascript;
//      Windows: powershell -Command "& {Start-Process …}").
//   4. Read the exported files, upload them via the platform's signed-URL
//      endpoint, and return [{ kind, url, metadata }] for /agent/complete.
//
// This is intentionally dependency-free — only Node built-ins + fetch.

import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TEMPLATES_DIR =
  process.env.LOVABLE_AGENT_TEMPLATES ||
  path.resolve(__dirname, "../../templates");

function resolveTemplatePath(sourceRef) {
  if (!sourceRef) throw new Error("template has no source_ref");
  // bridge://templates/CASE_STUDY_LETTER_MASTER_v001.ai
  const m = String(sourceRef).match(/^bridge:\/\/templates\/(.+)$/);
  if (!m) throw new Error(`unsupported source_ref: ${sourceRef}`);
  return path.join(TEMPLATES_DIR, m[1]);
}

function escapeForJsx(value) {
  return String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, "\\n");
}

function hexToRgb(hex) {
  const h = String(hex || "").replace("#", "");
  if (h.length !== 6) return null;
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

// Build an ExtendScript program. It walks every TextFrame / PathItem in the
// open document and replaces named layers with the job variables.
function buildJsx({ templatePath, variables, outDir }) {
  const assignments = Object.entries(variables || {})
    .map(([name, value]) => {
      const rgb = typeof value === "string" && value.startsWith("#") ? hexToRgb(value) : null;
      if (rgb) {
        return `vars["${escapeForJsx(name)}"] = { kind: "color", r: ${rgb.r}, g: ${rgb.g}, b: ${rgb.b} };`;
      }
      return `vars["${escapeForJsx(name)}"] = { kind: "text", value: "${escapeForJsx(value)}" };`;
    })
    .join("\n  ");

  return `
// Auto-generated by Lovable bridge agent
var vars = {};
${assignments}

var doc = app.open(new File("${escapeForJsx(templatePath)}"));

function applyToTextFrames(layer) {
  for (var i = 0; i < layer.textFrames.length; i++) {
    var tf = layer.textFrames[i];
    var key = tf.name || (tf.contents || "").replace(/^\\s+|\\s+$/g, "");
    if (vars[key] && vars[key].kind === "text") {
      tf.contents = vars[key].value;
    }
  }
  for (var j = 0; j < layer.layers.length; j++) {
    applyToTextFrames(layer.layers[j]);
  }
}

function applyColours(layer) {
  for (var i = 0; i < layer.pathItems.length; i++) {
    var p = layer.pathItems[i];
    if (vars[p.name] && vars[p.name].kind === "color") {
      var c = new RGBColor();
      c.red = vars[p.name].r;
      c.green = vars[p.name].g;
      c.blue = vars[p.name].b;
      if (p.filled) p.fillColor = c;
    }
  }
  for (var j = 0; j < layer.layers.length; j++) {
    applyColours(layer.layers[j]);
  }
}

for (var k = 0; k < doc.layers.length; k++) {
  applyToTextFrames(doc.layers[k]);
  applyColours(doc.layers[k]);
}

// Export PNG (web preview)
var pngFile = new File("${escapeForJsx(path.join(outDir, "preview.png"))}");
var pngOpts = new ExportOptionsPNG24();
pngOpts.antiAliasing = true;
pngOpts.transparency = false;
pngOpts.artBoardClipping = true;
doc.exportFile(pngFile, ExportType.PNG24, pngOpts);

// Save PDF (print master)
var pdfFile = new File("${escapeForJsx(path.join(outDir, "master.pdf"))}");
var pdfOpts = new PDFSaveOptions();
pdfOpts.pDFPreset = "[High Quality Print]";
doc.saveAs(pdfFile, pdfOpts);

// Save editable .ai copy (variables baked in, fonts/links still linked)
var aiFile = new File("${escapeForJsx(path.join(outDir, "editable.ai"))}");
var aiOpts = new IllustratorSaveOptions();
try { aiOpts.compatibility = Compatibility.ILLUSTRATOR17; } catch (e) {}
aiOpts.pdfCompatible = true;
doc.saveAs(aiFile, aiOpts);

// File > Package — collect Links + Fonts + report into <outDir>/package/
var pkgParent = new Folder("${escapeForJsx(outDir)}");
try {
  doc.packageDocument(pkgParent, "package", {
    copyLinks: true,
    copyFonts: true,
    copyProfiles: true,
    createReport: true,
    cleanStudentData: false,
    copyLinkedFiles: true,
    overwriteExisting: true
  });
} catch (e) {
  $.writeln("packageDocument failed: " + e);
}

doc.close(SaveOptions.DONOTSAVECHANGES);
`;
}

function runIllustratorScript(jsxPath) {
  return new Promise((resolve, reject) => {
    let cmd, args;
    if (process.platform === "darwin") {
      const apple = `tell application "Adobe Illustrator" to do javascript file "${jsxPath}"`;
      cmd = "osascript";
      args = ["-e", apple];
    } else if (process.platform === "win32") {
      // Illustrator on Windows is driven via the COM bridge; we shell out to
      // a tiny PowerShell wrapper.
      const ps = `$ai = New-Object -ComObject Illustrator.Application; $ai.DoJavaScriptFile("${jsxPath.replace(/\\/g, "\\\\")}")`;
      cmd = "powershell";
      args = ["-NoProfile", "-Command", ps];
    } else {
      return reject(new Error(`unsupported OS for Illustrator: ${process.platform}`));
    }
    const child = spawn(cmd, args, { stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code) =>
      code === 0 ? resolve() : reject(new Error(`Illustrator exited ${code}`)),
    );
  });
}

async function uploadOutput({ apiBase, token, jobId, filePath, kind, metadata }) {
  const filename = path.basename(filePath);
  const safe = filename.replace(/[^a-zA-Z0-9._-]/g, "_");
  const sigRes = await fetch(`${apiBase}/api/public/agent/upload-url`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({ jobId, filename: safe }),
  });
  if (!sigRes.ok) throw new Error(`upload-url ${sigRes.status}`);
  const sig = await sigRes.json();

  const body = await fs.readFile(filePath);
  const put = await fetch(sig.signed_url, {
    method: "PUT",
    headers: { "content-type": "application/octet-stream" },
    body,
  });
  if (!put.ok) throw new Error(`upload PUT ${put.status}`);

  return { kind, url: sig.public_url, metadata };
}

export async function run(job, ctx) {
  const { apiBase, token, progress } = ctx;
  await progress("opening", 10, "Opening template in Illustrator");

  const templatePath = resolveTemplatePath(job.template?.source_ref);
  await fs.access(templatePath).catch(() => {
    throw new Error(
      `Template not found locally: ${templatePath}. Place the .ai file in ${TEMPLATES_DIR} or set LOVABLE_AGENT_TEMPLATES.`,
    );
  });

  const outDir = await fs.mkdtemp(path.join(os.tmpdir(), `lovable-job-${job.id}-`));
  const jsxPath = path.join(outDir, "render.jsx");
  await fs.writeFile(jsxPath, buildJsx({ templatePath, variables: job.variables, outDir }));

  await progress("rendering", 40, "Running ExtendScript in Illustrator");
  await runIllustratorScript(jsxPath);

  await progress("uploading", 80, "Uploading artefacts");
  const outputs = [];
  outputs.push(
    await uploadOutput({
      apiBase, token, jobId: job.id,
      filePath: path.join(outDir, "preview.png"),
      kind: "png",
      metadata: { source: "illustrator" },
    }),
  );
  outputs.push(
    await uploadOutput({
      apiBase, token, jobId: job.id,
      filePath: path.join(outDir, "master.pdf"),
      kind: "pdf",
      metadata: { source: "illustrator" },
    }),
  );

  await progress("done", 100, "Outputs uploaded");
  return outputs;
}
