// Illustrator engine adapter — drives the desktop app via ExtendScript.
//
// Strategy:
//   1. Resolve the template's source .ai file from job.template.source_ref
//      (bridge://templates/<filename> → ./templates/<filename> relative to
//      LOVABLE_AGENT_TEMPLATES, default ./templates).
//   2. Render a .jsx script that opens the doc, substitutes text/colour layers
//      from job.variables, exports a PNG + PDF to a temp folder, then closes.
//   3. Invoke Illustrator with the script (macOS: osascript;
//      Windows: powershell -Command "& {Start-Process …}").
//   4. Read the exported files, upload them via the platform's signed-URL
//      endpoint, and return [{ kind, url, metadata }] for /agent/complete.
//
// This is intentionally dependency-free — only Node built-ins + fetch.

import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TEMPLATES_DIR =
  process.env.LOVABLE_AGENT_TEMPLATES ||
  path.resolve(__dirname, "../../templates");

function resolveTemplatePath(sourceRef) {
  if (!sourceRef) throw new Error("template has no source_ref");
  // bridge://templates/CASE_STUDY_LETTER_MASTER_v001.ai
  const m = String(sourceRef).match(/^bridge:\/\/templates\/(.+)$/);
  if (!m) throw new Error(`unsupported source_ref: ${sourceRef}`);
  return path.join(TEMPLATES_DIR, m[1]);
}

function escapeForJsx(value) {
  return String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, "\\n");
}

function hexToRgb(hex) {
  const h = String(hex || "").replace("#", "");
  if (h.length !== 6) return null;
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

// Build an ExtendScript program. It walks every TextFrame / PathItem in the
// open document and replaces named layers with the job variables. If the
// template declares `pages` (artboards), it exports one PNG per artboard plus
// a multi-page PDF covering every artboard.
function buildJsx({ templatePath, variables, outDir, pages }) {
  const assignments = Object.entries(variables || {})
    .map(([name, value]) => {
      const rgb = typeof value === "string" && value.startsWith("#") ? hexToRgb(value) : null;
      if (rgb) {
        return `vars["${escapeForJsx(name)}"] = { kind: "color", r: ${rgb.r}, g: ${rgb.g}, b: ${rgb.b} };`;
      }
      return `vars["${escapeForJsx(name)}"] = { kind: "text", value: "${escapeForJsx(value)}" };`;
    })
    .join("\n  ");

  const pageList = Array.isArray(pages) && pages.length > 0 ? pages : null;
  const artboardIndexes = pageList
    ? pageList.map((p, i) => Number.isInteger(p.artboard_index) ? p.artboard_index : i)
    : null;
  const pageNames = pageList ? pageList.map((p, i) => p.name || `page_${i + 1}`) : null;

  return `
// Auto-generated by Lovable bridge agent
var vars = {};
${assignments}

var doc = app.open(new File("${escapeForJsx(templatePath)}"));

function applyToTextFrames(layer) {
  for (var i = 0; i < layer.textFrames.length; i++) {
    var tf = layer.textFrames[i];
    var key = tf.name || (tf.contents || "").replace(/^\\s+|\\s+$/g, "");
    if (vars[key] && vars[key].kind === "text") {
      tf.contents = vars[key].value;
    }
  }
  for (var j = 0; j < layer.layers.length; j++) {
    applyToTextFrames(layer.layers[j]);
  }
}

function applyColours(layer) {
  for (var i = 0; i < layer.pathItems.length; i++) {
    var p = layer.pathItems[i];
    if (vars[p.name] && vars[p.name].kind === "color") {
      var c = new RGBColor();
      c.red = vars[p.name].r;
      c.green = vars[p.name].g;
      c.blue = vars[p.name].b;
      if (p.filled) p.fillColor = c;
    }
  }
  for (var j = 0; j < layer.layers.length; j++) {
    applyColours(layer.layers[j]);
  }
}

for (var k = 0; k < doc.layers.length; k++) {
  applyToTextFrames(doc.layers[k]);
  applyColours(doc.layers[k]);
}

// --- Per-artboard PNG export -------------------------------------------------
var pngOpts = new ExportOptionsPNG24();
pngOpts.antiAliasing = true;
pngOpts.transparency = false;
pngOpts.artBoardClipping = true;

var indices = ${JSON.stringify(artboardIndexes ?? [0])};
var names = ${JSON.stringify(pageNames ?? ["preview"])};
var pad = function (n) { return (n < 10 ? "0" : "") + n; };
var slug = function (s) { return String(s).replace(/[^a-zA-Z0-9_-]+/g, "_").toLowerCase(); };

for (var ai = 0; ai < indices.length; ai++) {
  var idx = indices[ai];
  if (idx < doc.artboards.length) {
    doc.artboards.setActiveArtboardIndex(idx);
  }
  var filename = ${pageList ? "'page_' + pad(ai + 1) + '_' + slug(names[ai]) + '.png'" : "'preview.png'"};
  var pngFile = new File("${escapeForJsx(outDir)}/" + filename);
  doc.exportFile(pngFile, ExportType.PNG24, pngOpts);
}

// Keep a top-level preview.png that points at page 1 for thumbnails.
if (indices.length > 1) {
  var firstName = 'page_01_' + slug(names[0]) + '.png';
  var src = new File("${escapeForJsx(outDir)}/" + firstName);
  var dst = new File("${escapeForJsx(outDir)}/preview.png");
  try { src.copy(dst); } catch (e) {}
}

// --- Multi-page PDF (one PDF, every artboard) --------------------------------
var pdfFile = new File("${escapeForJsx(path.join(outDir, "master.pdf"))}");
var pdfOpts = new PDFSaveOptions();
pdfOpts.pDFPreset = "[High Quality Print]";
try {
  pdfOpts.artboardRange = ""; // empty = all artboards
} catch (e) {}
doc.saveAs(pdfFile, pdfOpts);

// --- Editable .ai copy -------------------------------------------------------
var aiFile = new File("${escapeForJsx(path.join(outDir, "editable.ai"))}");
var aiOpts = new IllustratorSaveOptions();
try { aiOpts.compatibility = Compatibility.ILLUSTRATOR17; } catch (e) {}
aiOpts.pdfCompatible = true;
doc.saveAs(aiFile, aiOpts);

// --- File > Package ----------------------------------------------------------
var pkgParent = new Folder("${escapeForJsx(outDir)}");
try {
  doc.packageDocument(pkgParent, "package", {
    copyLinks: true,
    copyFonts: true,
    copyProfiles: true,
    createReport: true,
    cleanStudentData: false,
    copyLinkedFiles: true,
    overwriteExisting: true
  });
} catch (e) {
  $.writeln("packageDocument failed: " + e);
}

doc.close(SaveOptions.DONOTSAVECHANGES);
`;
}

function runIllustratorScript(jsxPath) {
  return new Promise((resolve, reject) => {
    let cmd, args;
    if (process.platform === "darwin") {
      const apple = `tell application "Adobe Illustrator" to do javascript file "${jsxPath}"`;
      cmd = "osascript";
      args = ["-e", apple];
    } else if (process.platform === "win32") {
      // Illustrator on Windows is driven via the COM bridge; we shell out to
      // a tiny PowerShell wrapper.
      const ps = `$ai = New-Object -ComObject Illustrator.Application; $ai.DoJavaScriptFile("${jsxPath.replace(/\\/g, "\\\\")}")`;
      cmd = "powershell";
      args = ["-NoProfile", "-Command", ps];
    } else {
      return reject(new Error(`unsupported OS for Illustrator: ${process.platform}`));
    }
    const child = spawn(cmd, args, { stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code) =>
      code === 0 ? resolve() : reject(new Error(`Illustrator exited ${code}`)),
    );
  });
}

async function uploadOutput({ apiBase, token, jobId, filePath, kind, metadata }) {
  const filename = path.basename(filePath);
  const safe = filename.replace(/[^a-zA-Z0-9._-]/g, "_");
  const sigRes = await fetch(`${apiBase}/api/public/agent/upload-url`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({ jobId, filename: safe }),
  });
  if (!sigRes.ok) throw new Error(`upload-url ${sigRes.status}`);
  const sig = await sigRes.json();

  const body = await fs.readFile(filePath);
  const put = await fetch(sig.signed_url, {
    method: "PUT",
    headers: { "content-type": "application/octet-stream" },
    body,
  });
  if (!put.ok) throw new Error(`upload PUT ${put.status}`);

  return { kind, url: sig.public_url, metadata };
}

// Zip a folder using the OS's native tool (no npm deps).
//   macOS/Linux: /usr/bin/zip
//   Windows:     PowerShell Compress-Archive
function zipFolder(srcDir, zipPath) {
  return new Promise((resolve, reject) => {
    let cmd, args, opts = { stdio: "inherit" };
    if (process.platform === "win32") {
      cmd = "powershell";
      args = [
        "-NoProfile",
        "-Command",
        `Compress-Archive -Path '${srcDir}\\*' -DestinationPath '${zipPath}' -Force`,
      ];
    } else {
      cmd = "zip";
      args = ["-r", "-q", zipPath, "."];
      opts.cwd = srcDir;
    }
    const child = spawn(cmd, args, opts);
    child.on("error", reject);
    child.on("exit", (code) =>
      code === 0 ? resolve() : reject(new Error(`zip exited ${code}`)),
    );
  });
}

async function safeUpload(args) {
  try { return await uploadOutput(args); }
  catch (e) {
    console.warn(`upload failed for ${args.filePath}: ${e.message}`);
    return null;
  }
}

export async function run(job, ctx) {
  const { apiBase, token, progress } = ctx;
  await progress("opening", 10, "Opening template in Illustrator");

  const templatePath = resolveTemplatePath(job.template?.source_ref);
  await fs.access(templatePath).catch(() => {
    throw new Error(
      `Template not found locally: ${templatePath}. Place the .ai file in ${TEMPLATES_DIR} or set LOVABLE_AGENT_TEMPLATES.`,
    );
  });

  const outDir = await fs.mkdtemp(path.join(os.tmpdir(), `lovable-job-${job.id}-`));
  const jsxPath = path.join(outDir, "render.jsx");
  const pages = Array.isArray(job.template?.pages) ? job.template.pages : [];
  await fs.writeFile(
    jsxPath,
    buildJsx({ templatePath, variables: job.variables, outDir, pages }),
  );

  await progress("rendering", 40, `Rendering ${pages.length || 1} page(s) in Illustrator`);
  await runIllustratorScript(jsxPath);

  // Discover per-page PNGs the script just wrote.
  const all = await fs.readdir(outDir);
  const pagePngs = all
    .filter((f) => /^page_\d+_.*\.png$/.test(f))
    .sort();

  // Write a manifest into the package folder before zipping.
  const pkgDir = path.join(outDir, "package");
  await fs.mkdir(pkgDir, { recursive: true });
  try { await fs.copyFile(path.join(outDir, "editable.ai"), path.join(pkgDir, "editable.ai")); } catch {}
  try { await fs.copyFile(path.join(outDir, "master.pdf"), path.join(pkgDir, "master.pdf")); } catch {}
  try { await fs.copyFile(path.join(outDir, "preview.png"), path.join(pkgDir, "preview.png")); } catch {}
  for (const png of pagePngs) {
    try { await fs.copyFile(path.join(outDir, png), path.join(pkgDir, png)); } catch {}
  }

  await fs.writeFile(
    path.join(pkgDir, "manifest.json"),
    JSON.stringify(
      {
        job_id: job.id,
        template: job.template?.name ?? null,
        source_ref: job.template?.source_ref ?? null,
        engine: "illustrator",
        rendered_at: new Date().toISOString(),
        page_count: pages.length || 1,
        pages: pages.length
          ? pages.map((p, i) => ({
              index: i + 1,
              name: p.name ?? `page_${i + 1}`,
              file: pagePngs[i] ?? null,
              width: p.width, height: p.height, unit: p.unit,
            }))
          : [{ index: 1, name: "preview", file: "preview.png" }],
        variables: job.variables ?? {},
      },
      null,
      2,
    ),
  );

  await progress("packaging", 75, "Zipping editable assets + fonts");
  const zipPath = path.join(outDir, "package.zip");
  try { await zipFolder(pkgDir, zipPath); }
  catch (e) { console.warn(`package zip failed: ${e.message}`); }

  await progress("uploading", 85, `Uploading ${pagePngs.length || 1} page(s) + artefacts`);
  const outputs = [];

  // Per-page PNGs (if any) — keep the cover/page-1 as the primary thumbnail.
  for (let i = 0; i < pagePngs.length; i++) {
    const filePath = path.join(outDir, pagePngs[i]);
    const meta = {
      source: "illustrator",
      page_index: i + 1,
      page_name: pages[i]?.name ?? null,
      total_pages: pagePngs.length,
    };
    const up = await safeUpload({ apiBase, token, jobId: job.id, filePath, kind: "png", metadata: meta });
    if (up) outputs.push(up);
  }
  if (pagePngs.length === 0) {
    const png = await safeUpload({
      apiBase, token, jobId: job.id,
      filePath: path.join(outDir, "preview.png"),
      kind: "png",
      metadata: { source: "illustrator", page_index: 1, total_pages: 1 },
    });
    if (png) outputs.push(png);
  }

  const pdf = await safeUpload({
    apiBase, token, jobId: job.id,
    filePath: path.join(outDir, "master.pdf"),
    kind: "pdf",
    metadata: { source: "illustrator", page_count: pages.length || 1 },
  });
  if (pdf) outputs.push(pdf);

  const ai = await safeUpload({
    apiBase, token, jobId: job.id,
    filePath: path.join(outDir, "editable.ai"),
    kind: "ai",
    metadata: { source: "illustrator", editable: true },
  });
  if (ai) outputs.push(ai);

  if (await fs.stat(zipPath).then(() => true).catch(() => false)) {
    const pkg = await safeUpload({
      apiBase, token, jobId: job.id,
      filePath: zipPath,
      kind: "package",
      metadata: {
        source: "illustrator",
        page_count: pages.length || 1,
        contents: [
          "editable.ai", "master.pdf", "preview.png",
          ...pagePngs,
          "Links/", "Fonts/", "manifest.json", "Report.txt",
        ],
      },
    });
    if (pkg) outputs.push(pkg);
  }

  await progress("done", 100, "Outputs uploaded");
  return outputs;
}

