/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOutputsRouteImport } from './routes/_authenticated/outputs'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings.api'
import { Route as AuthenticatedSettingsAgentRouteImport } from './routes/_authenticated/settings.agent'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as ApiPublicV1JobsRouteImport } from './routes/api/public/v1/jobs'
import { Route as ApiPublicAgentPingRouteImport } from './routes/api/public/agent/ping'
import { Route as ApiPublicAgentCompleteRouteImport } from './routes/api/public/agent/complete'
import { Route as ApiPublicAgentClaimRouteImport } from './routes/api/public/agent/claim'
import { Route as ApiPublicV1JobsJobIdRouteImport } from './routes/api/public/v1/jobs.$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutputsRoute = AuthenticatedOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/settings/api',
    path: '/settings/api',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAgentRoute =
  AuthenticatedSettingsAgentRouteImport.update({
    id: '/settings/agent',
    path: '/settings/agent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const ApiPublicV1JobsRoute = ApiPublicV1JobsRouteImport.update({
  id: '/api/public/v1/jobs',
  path: '/api/public/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPingRoute = ApiPublicAgentPingRouteImport.update({
  id: '/api/public/agent/ping',
  path: '/api/public/agent/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCompleteRoute = ApiPublicAgentCompleteRouteImport.update({
  id: '/api/public/agent/complete',
  path: '/api/public/agent/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentClaimRoute = ApiPublicAgentClaimRouteImport.update({
  id: '/api/public/agent/claim',
  path: '/api/public/agent/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1JobsJobIdRoute = ApiPublicV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiPublicV1JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/outputs': typeof AuthenticatedOutputsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/outputs'
    | '/projects'
    | '/templates'
    | '/projects/$projectId'
    | '/settings/agent'
    | '/settings/api'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/ping'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/outputs'
    | '/projects'
    | '/templates'
    | '/projects/$projectId'
    | '/settings/agent'
    | '/settings/api'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/ping'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/outputs'
    | '/_authenticated/projects'
    | '/_authenticated/templates'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/agent'
    | '/_authenticated/settings/api'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/ping'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentClaimRoute: typeof ApiPublicAgentClaimRoute
  ApiPublicAgentCompleteRoute: typeof ApiPublicAgentCompleteRoute
  ApiPublicAgentPingRoute: typeof ApiPublicAgentPingRoute
  ApiPublicV1JobsRoute: typeof ApiPublicV1JobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outputs': {
      id: '/_authenticated/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof AuthenticatedOutputsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/agent': {
      id: '/_authenticated/settings/agent'
      path: '/settings/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof AuthenticatedSettingsAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/api/public/v1/jobs': {
      id: '/api/public/v1/jobs'
      path: '/api/public/v1/jobs'
      fullPath: '/api/public/v1/jobs'
      preLoaderRoute: typeof ApiPublicV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/ping': {
      id: '/api/public/agent/ping'
      path: '/api/public/agent/ping'
      fullPath: '/api/public/agent/ping'
      preLoaderRoute: typeof ApiPublicAgentPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/complete': {
      id: '/api/public/agent/complete'
      path: '/api/public/agent/complete'
      fullPath: '/api/public/agent/complete'
      preLoaderRoute: typeof ApiPublicAgentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/claim': {
      id: '/api/public/agent/claim'
      path: '/api/public/agent/claim'
      fullPath: '/api/public/agent/claim'
      preLoaderRoute: typeof ApiPublicAgentClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/jobs/$jobId': {
      id: '/api/public/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/public/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiPublicV1JobsJobIdRouteImport
      parentRoute: typeof ApiPublicV1JobsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOutputsRoute: typeof AuthenticatedOutputsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedSettingsAgentRoute: typeof AuthenticatedSettingsAgentRoute
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOutputsRoute: AuthenticatedOutputsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedSettingsAgentRoute: AuthenticatedSettingsAgentRoute,
  AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1JobsRouteChildren {
  ApiPublicV1JobsJobIdRoute: typeof ApiPublicV1JobsJobIdRoute
}

const ApiPublicV1JobsRouteChildren: ApiPublicV1JobsRouteChildren = {
  ApiPublicV1JobsJobIdRoute: ApiPublicV1JobsJobIdRoute,
}

const ApiPublicV1JobsRouteWithChildren = ApiPublicV1JobsRoute._addFileChildren(
  ApiPublicV1JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentClaimRoute: ApiPublicAgentClaimRoute,
  ApiPublicAgentCompleteRoute: ApiPublicAgentCompleteRoute,
  ApiPublicAgentPingRoute: ApiPublicAgentPingRoute,
  ApiPublicV1JobsRoute: ApiPublicV1JobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
