/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOutputsRouteImport } from './routes/_authenticated/outputs'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedExamplesRouteImport } from './routes/_authenticated/examples'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates.$templateId'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings.api'
import { Route as AuthenticatedSettingsAgentRouteImport } from './routes/_authenticated/settings.agent'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as ApiPublicV1JobsRouteImport } from './routes/api/public/v1/jobs'
import { Route as ApiPublicAgentUploadUrlRouteImport } from './routes/api/public/agent/upload-url'
import { Route as ApiPublicAgentProgressRouteImport } from './routes/api/public/agent/progress'
import { Route as ApiPublicAgentPingRouteImport } from './routes/api/public/agent/ping'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentCompleteRouteImport } from './routes/api/public/agent/complete'
import { Route as ApiPublicAgentClaimRouteImport } from './routes/api/public/agent/claim'
import { Route as ApiPublicV1JobsJobIdRouteImport } from './routes/api/public/v1/jobs.$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutputsRoute = AuthenticatedOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamplesRoute = AuthenticatedExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/settings/api',
    path: '/settings/api',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAgentRoute =
  AuthenticatedSettingsAgentRouteImport.update({
    id: '/settings/agent',
    path: '/settings/agent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const ApiPublicV1JobsRoute = ApiPublicV1JobsRouteImport.update({
  id: '/api/public/v1/jobs',
  path: '/api/public/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUploadUrlRoute = ApiPublicAgentUploadUrlRouteImport.update({
  id: '/api/public/agent/upload-url',
  path: '/api/public/agent/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentProgressRoute = ApiPublicAgentProgressRouteImport.update({
  id: '/api/public/agent/progress',
  path: '/api/public/agent/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPingRoute = ApiPublicAgentPingRouteImport.update({
  id: '/api/public/agent/ping',
  path: '/api/public/agent/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCompleteRoute = ApiPublicAgentCompleteRouteImport.update({
  id: '/api/public/agent/complete',
  path: '/api/public/agent/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentClaimRoute = ApiPublicAgentClaimRouteImport.update({
  id: '/api/public/agent/claim',
  path: '/api/public/agent/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1JobsJobIdRoute = ApiPublicV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiPublicV1JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/examples': typeof AuthenticatedExamplesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/agent/progress': typeof ApiPublicAgentProgressRoute
  '/api/public/agent/upload-url': typeof ApiPublicAgentUploadUrlRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/examples': typeof AuthenticatedExamplesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/agent/progress': typeof ApiPublicAgentProgressRoute
  '/api/public/agent/upload-url': typeof ApiPublicAgentUploadUrlRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/examples': typeof AuthenticatedExamplesRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/outputs': typeof AuthenticatedOutputsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/agent': typeof AuthenticatedSettingsAgentRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/claim': typeof ApiPublicAgentClaimRoute
  '/api/public/agent/complete': typeof ApiPublicAgentCompleteRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
  '/api/public/agent/progress': typeof ApiPublicAgentProgressRoute
  '/api/public/agent/upload-url': typeof ApiPublicAgentUploadUrlRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brands'
    | '/dashboard'
    | '/examples'
    | '/jobs'
    | '/library'
    | '/outputs'
    | '/projects'
    | '/projects/$projectId'
    | '/settings/agent'
    | '/settings/api'
    | '/settings/integrations'
    | '/templates/$templateId'
    | '/templates/'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ping'
    | '/api/public/agent/progress'
    | '/api/public/agent/upload-url'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brands'
    | '/dashboard'
    | '/examples'
    | '/jobs'
    | '/library'
    | '/outputs'
    | '/projects'
    | '/projects/$projectId'
    | '/settings/agent'
    | '/settings/api'
    | '/settings/integrations'
    | '/templates/$templateId'
    | '/templates'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ping'
    | '/api/public/agent/progress'
    | '/api/public/agent/upload-url'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/_authenticated/examples'
    | '/_authenticated/jobs'
    | '/_authenticated/library'
    | '/_authenticated/outputs'
    | '/_authenticated/projects'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/agent'
    | '/_authenticated/settings/api'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/templates/'
    | '/api/public/agent/claim'
    | '/api/public/agent/complete'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ping'
    | '/api/public/agent/progress'
    | '/api/public/agent/upload-url'
    | '/api/public/v1/jobs'
    | '/api/public/v1/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentClaimRoute: typeof ApiPublicAgentClaimRoute
  ApiPublicAgentCompleteRoute: typeof ApiPublicAgentCompleteRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentPingRoute: typeof ApiPublicAgentPingRoute
  ApiPublicAgentProgressRoute: typeof ApiPublicAgentProgressRoute
  ApiPublicAgentUploadUrlRoute: typeof ApiPublicAgentUploadUrlRoute
  ApiPublicV1JobsRoute: typeof ApiPublicV1JobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outputs': {
      id: '/_authenticated/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof AuthenticatedOutputsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/examples': {
      id: '/_authenticated/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof AuthenticatedExamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/agent': {
      id: '/_authenticated/settings/agent'
      path: '/settings/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof AuthenticatedSettingsAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/api/public/v1/jobs': {
      id: '/api/public/v1/jobs'
      path: '/api/public/v1/jobs'
      fullPath: '/api/public/v1/jobs'
      preLoaderRoute: typeof ApiPublicV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/upload-url': {
      id: '/api/public/agent/upload-url'
      path: '/api/public/agent/upload-url'
      fullPath: '/api/public/agent/upload-url'
      preLoaderRoute: typeof ApiPublicAgentUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/progress': {
      id: '/api/public/agent/progress'
      path: '/api/public/agent/progress'
      fullPath: '/api/public/agent/progress'
      preLoaderRoute: typeof ApiPublicAgentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/ping': {
      id: '/api/public/agent/ping'
      path: '/api/public/agent/ping'
      fullPath: '/api/public/agent/ping'
      preLoaderRoute: typeof ApiPublicAgentPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/complete': {
      id: '/api/public/agent/complete'
      path: '/api/public/agent/complete'
      fullPath: '/api/public/agent/complete'
      preLoaderRoute: typeof ApiPublicAgentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/claim': {
      id: '/api/public/agent/claim'
      path: '/api/public/agent/claim'
      fullPath: '/api/public/agent/claim'
      preLoaderRoute: typeof ApiPublicAgentClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/jobs/$jobId': {
      id: '/api/public/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/public/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiPublicV1JobsJobIdRouteImport
      parentRoute: typeof ApiPublicV1JobsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamplesRoute: typeof AuthenticatedExamplesRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOutputsRoute: typeof AuthenticatedOutputsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsAgentRoute: typeof AuthenticatedSettingsAgentRoute
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamplesRoute: AuthenticatedExamplesRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOutputsRoute: AuthenticatedOutputsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsAgentRoute: AuthenticatedSettingsAgentRoute,
  AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1JobsRouteChildren {
  ApiPublicV1JobsJobIdRoute: typeof ApiPublicV1JobsJobIdRoute
}

const ApiPublicV1JobsRouteChildren: ApiPublicV1JobsRouteChildren = {
  ApiPublicV1JobsJobIdRoute: ApiPublicV1JobsJobIdRoute,
}

const ApiPublicV1JobsRouteWithChildren = ApiPublicV1JobsRoute._addFileChildren(
  ApiPublicV1JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentClaimRoute: ApiPublicAgentClaimRoute,
  ApiPublicAgentCompleteRoute: ApiPublicAgentCompleteRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentPingRoute: ApiPublicAgentPingRoute,
  ApiPublicAgentProgressRoute: ApiPublicAgentProgressRoute,
  ApiPublicAgentUploadUrlRoute: ApiPublicAgentUploadUrlRoute,
  ApiPublicV1JobsRoute: ApiPublicV1JobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
